### GET ARTICLES
GET http://localhost:3120/articles?search=%23tutorial


### popular articles
GET http://localhost:3120/articles/popular


### SHOW ARTICLES

GET http://localhost:3120/article/how-to-install-node-js-simply

### GET ALL CATEGORIES

GET http://localhost:3120/categories







