### GET ARTICLES
GET http://localhost:3120/articles


### popular articles
GET http://localhost:3120/articles/popular


### SHOW ARTICLES

GET http://localhost:3120/article/how-to-install-node-js-simply

### GET ALL CATEGORIES

GET http://localhost:3120/categories

### LOGIN
post http://localhost:3120/login
Content-Type: application/json
Accept: application/json

{
  "username" : "menzcreate",
  "password" : "tes123"
}

### create article
POST http://localhost:3120/articles/create
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJtZW56Y3JlYXRlIiwiZW1haWwiOiJJbG1hbnN1bmFubnVkaW4yQGdtYWlsLmNvbSIsImZ1bGxfbmFtZSI6IklsbWFuIFMiLCJpYXQiOjE2ODgzMjEyNDQsImV4cCI6MTY4ODQwNzY0NH0.paB8cI7h5ttpBDtk1WdBmRxYRqGqhyRP4v3fj9nYMNI

{
  "title" : "Testing api2",
  "categoryId" : 1,
  "body" : "okeokeokeokeosf"
}

### delete article

DELETE http://localhost:3120/articles
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJtZW56Y3JlYXRlIiwiZW1haWwiOiJJbG1hbnN1bmFubnVkaW4yQGdtYWlsLmNvbSIsImZ1bGxfbmFtZSI6IklsbWFuIFMiLCJpYXQiOjE2ODgzMjEyNDQsImV4cCI6MTY4ODQwNzY0NH0.paB8cI7h5ttpBDtk1WdBmRxYRqGqhyRP4v3fj9nYMNI

{
  "articleId" : 34
}







